import Main from '../components/Main'
import Head from 'next/head'
import Projects from '../components/Projects'
import Contacts from '../components/Contacts'
import Shop from "../components/Shop"



export default function Home() {
  return (
    <div>
      <Head>
        <title> Blockchain Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
      {/* <Shop /> */}
      <Projects />
      <Contacts />


      


    </div>
  )
}
